# Generated by Django 3.0.2 on 2020-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_auto_20200426_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(null=True)),
                ('link', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contact_Us',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
